name: "Software's Giant Leap"
description: "The story of how the Apollo missions changed software"
meta_description: "The software that guided humans to the Moon was one of the greatest innovations developed during the Apollo program. It introduced concepts still reflected in modern operating systems and programming languages like Linux and Python."

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

logo: false
baseurl: /
domain_name: 'https://softwaresgiantleap.github.io'
google_analytics: 'UA-60067944-2'

# Details for the RSS feed generator
url:            'https://softwaresgiantleap.github.io'
author:         'Joe Kutner'
